### ISSUE TITLE
Implement ToR-Stats functionality

### ISSUE THREAD

**Issue by MaxVanDeursen** [GrafeasGroup/buttercup#11]
Using the current implementation of [ToR-Stats](https://github.com/DavidArchibald/ToR-Bots) and Blossom, implement the functionality within ButterCup. Below is a list of all functionality that ToR-Stats currently provides, along with a short description. Moreover, a short overview of API functionality that is required from Blossom is highlighted.

Graphical commands: 
- [x] `all_history [start] [end]` and `history [redditors] [start] [end]`: Provides the cumulative gammas per day in a plot, with optional arguments for both start and end dates. `all_history` provides an aggregate over all users and `history` provides the individual results instead. This could be implemented in `Blossom` by an API call with arguments for start and end dates, along with an optional list of redditors. If this list is empty, the aggregate can be returned. This would then contain the counts for each day.
- [x] `all_rate` and `rate [redditor] [start] [end]`: Provides the rate of gammas per day in a plot, with optional arguments for both start and end days. Once again `all_rate` provides an aggregate over all users, where `rate` provides individual results. The same call described above can be used in Blossom to achieve this graph. I would moreover introduce the same signature as `all_history` and `history`.
- [x] `context_history [redditor] [start] [end]`: Equal to `history`, but with the y axis showing all ranks. Can be done similarly to the above implementations.
- [ ] `distribution`: Shows the cumulative distribution of number of transcribers on the x-axis and number of transcriptions on the y-axis. For this data the totals for all users would be required.

Textual commands:
- [x] `all_stats` and `tor_stats [redditor]`: Shows the aggregated stats summary of the transcribers, either aggregated of of a specific redditor. The stats shown are: gamma count, number of seen transcriptions, total characters, total upvotes, good bots, bad bots, good humans, and bad humans. Currently the upvotes and comments are not considered in Blossom and the question is whether we want to scrape this for all transcriptions. The other statistics can be extracted from Blossom easily, where I would say a summary API call which provides these available statistics is sufficient.
- [x] `gammas/leaderboard/lb [redditor] [context]`: Provides a leaderboard showing the top 6, as well as a local leaderboard around the user, of which context provides the number of ranks shown locally. This requires this information of Blossom. I would probably think a similar leaderboard could be returned by Blossom, where the same arguments are used.
- [x] `permalink [thread]`: Provides a Reddit permalink to a thread.
- [x] `ping`: pong
- [x] `progress [redditor] [hours]`: Shows the number of transcriptions done in the last provided hours for the specified redditor. Since this is used for the 100/24 challenge, I think its best to have a separate API call with Blossom to provide an accurate number from the current time.
- [x] `server_info`: Provides a String with server info
- [x] `source [post_url]`: Provides the source of the provided URL.
- [x] `until/to [future_gamma]`: Provides an estimation of time of how long it takes to achieve the future gamma based on the transcriptions in the last 48 hours.

I would recommend generalizing the signatures of all commands to allow a search on another redditor.

**Comment by TimJentzsch** [comment]
We implemented all important (often used) commands and I created individual issues for all of them.
So I think we're good to close this one.
