### ISSUE TITLE
Add `/time` command

### ISSUE THREAD

**Issue by TimJentzsch** [GrafeasGroup/buttercup#39]
Add a `/time` command to convert between time zones. This has often been a pain to do manually, e.g. for community events.
This command should use the time zone specified in the display name, if available.

It should convert the given time in the most common time zones, e.g.:

> 13:00 UTC-2 in other time zones:
>
> 07:00 UTC-08:00 (PST)
> 08:00 UTC-07:00 (MST)
> 09:00 UTC-06:00 (CST)
> 10:00 UTC-05:00 (EST)
> 15:00 UTC+00:00 (UTC/GMT/WET)
> 16:00 UTC+01:00 (CET/WAT)
> 17:00 UTC+02:00 (CEST/EET)
> 18:00 UTC+03:00 (MSK/EAT)
> 00:00 UTC+09:00 (AWST)
> 00:30 UTC+09:30 (ACST)
> 01:00 UTC+10:00 (AEST)

**Options**:
- `time`: The time to convert to other time zones.
- `time zone` (optional): The time zone used in the provided time. Defaults to the time zone specified by the user executing the command or UTC if not available.

**Comment by Tyrannicodin** [comment]
Can't this be done automatically through discord events now?

**Comment by TimJentzsch** [comment]
True, and localized times can be embedded in the text.
We don't need this anymore.
